<?php
header("Access-Control-Allow-Origin: *");
require_once("tcpdf.php");
require_once("fpdi/fpdi.php");
// สร้างคลาสที่สืบทอดมาจาก TCPDF
class MyPDF extends TCPDF {
    public function Header() {
        // กำหนดเนื้อหาส่วน Header
    }
    
    public function Footer() {
        // กำหนดเนื้อหาส่วน Footer
    }
}
// สร้างเอกสาร PDF ด้วยคลาสที่สร้างขึ้น
$pdf = new MyPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// กำหนดเนื้อหาของ PDF
$pdf->SetTitle('My First TCPDF');
$pdf->SetHeaderData('', '', 'My First TCPDF', 'Generated by TCPDF', array(0,64,255), array(0,64,128));
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// เพิ่มหน้าใน PDF
$pdf->AddPage();

// เพิ่มเนื้อหาลงใน PDF
$pdf->SetFont('times', 'BI', 12);
$pdf->Cell(0, 10, 'Hello, TCPDF!', 0, 1, 'C');

// สร้างไฟล์ PDF
$pdf->Output('my_first_tcpdf.pdf', 'I'); // I: แสดงที่เบราว์เซอร์, D: ดาวน์โหลด, F: บันทึกไปยังไฟล์
?>